package com.redz.financeportfolio.util;

import java.util.List;
import java.util.Map;

public class Companies {

    public static List<Map<String, String>> getAll() {
        return List.of(
                Map.of("symbol", "AAPL", "name", "Apple Inc."),
                Map.of("symbol", "AMZN", "name", "Amazon.com Inc."),
                Map.of("symbol", "GOOGL", "name", "Alphabet Inc. (Google)"),
                Map.of("symbol", "MSFT", "name", "Microsoft Corporation"),
                Map.of("symbol", "TSLA", "name", "Tesla, Inc."),
                Map.of("symbol", "NFLX", "name", "Netflix, Inc."),
                Map.of("symbol", "FB", "name", "Meta Platforms (Facebook)"),
                Map.of("symbol", "NVDA", "name", "NVIDIA Corporation"),
                Map.of("symbol", "BA", "name", "The Boeing Company"),
                Map.of("symbol", "DIS", "name", "The Walt Disney Company"),
                Map.of("symbol", "IBM", "name", "International Business Machines Corporation"),
                Map.of("symbol", "SPY", "name", "SPDR S&P 500 ETF Trust"),
                Map.of("symbol", "GOOG", "name", "Alphabet Inc. (Google Class C)"),
                Map.of("symbol", "INTC", "name", "Intel Corporation"),
                Map.of("symbol", "GS", "name", "Goldman Sachs Group, Inc."),
                Map.of("symbol", "AMD", "name", "Advanced Micro Devices, Inc."),
                Map.of("symbol", "BABA", "name", "Alibaba Group"),
                Map.of("symbol", "V", "name", "Visa Inc."),
                Map.of("symbol", "PYPL", "name", "PayPal Holdings, Inc."),
                Map.of("symbol", "KO", "name", "Coca-Cola Company"),
                Map.of("symbol", "TSM", "name", "Taiwan Semiconductor Manufacturing Company"),
                Map.of("symbol", "PFE", "name", "Pfizer Inc."),
                Map.of("symbol", "JNJ", "name", "Johnson & Johnson"),
                Map.of("symbol", "WMT", "name", "Walmart Inc."),
                Map.of("symbol", "GE", "name", "General Electric"),
                Map.of("symbol", "COST", "name", "Costco Wholesale Corporation"),
                Map.of("symbol", "ORCL", "name", "Oracle Corporation"),
                Map.of("symbol", "CVX", "name", "Chevron Corporation"),
                Map.of("symbol", "XOM", "name", "Exxon Mobil Corporation"),
                Map.of("symbol", "MMM", "name", "3M Company"),
                Map.of("symbol", "LMT", "name", "Lockheed Martin Corporation"),
                Map.of("symbol", "MCD", "name", "McDonald's Corporation"),
                Map.of("symbol", "NKE", "name", "Nike, Inc."),
                Map.of("symbol", "AXP", "name", "American Express Company"),
                Map.of("symbol", "GS", "name", "Goldman Sachs Group, Inc."),
                Map.of("symbol", "BA", "name", "Boeing Co."),
                Map.of("symbol", "T", "name", "AT&T Inc."),
                Map.of("symbol", "VZ", "name", "Verizon Communications Inc."),
                Map.of("symbol", "CAT", "name", "Caterpillar Inc."),
                Map.of("symbol", "F", "name", "Ford Motor Company"),
                Map.of("symbol", "ZTS", "name", "Zoetis Inc."),
                Map.of("symbol", "MU", "name", "Micron Technology, Inc."),
                Map.of("symbol", "TMO", "name", "Thermo Fisher Scientific Inc."),
                Map.of("symbol", "ADBE", "name", "Adobe Inc."),
                Map.of("symbol", "CSCO", "name", "Cisco Systems, Inc."),
                Map.of("symbol", "AMAT", "name", "Applied Materials, Inc."),
                Map.of("symbol", "MDT", "name", "Medtronic plc"),
                Map.of("symbol", "BMY", "name", "Bristol-Myers Squibb Company"),
                Map.of("symbol", "CVS", "name", "CVS Health Corporation"),
                Map.of("symbol", "UNH", "name", "UnitedHealth Group Incorporated"),
                Map.of("symbol", "NEE", "name", "NextEra Energy, Inc."),
                Map.of("symbol", "BNS", "name", "Bank of Nova Scotia"),
                Map.of("symbol", "AXP", "name", "American Express"),
                Map.of("symbol", "MRK", "name", "Merck & Co., Inc."),
                Map.of("symbol", "HON", "name", "Honeywell International Inc."),
                Map.of("symbol", "MELI", "name", "Mercado Libre, Inc."),
                Map.of("symbol", "ROST", "name", "Ross Stores, Inc."),
                Map.of("symbol", "LOW", "name", "Lowe's Companies, Inc."),
                Map.of("symbol", "WFC", "name", "Wells Fargo & Company"),
                Map.of("symbol", "SCHW", "name", "Charles Schwab Corporation"),
                Map.of("symbol", "PLD", "name", "Prologis, Inc."),
                Map.of("symbol", "CME", "name", "CME Group Inc."),
                Map.of("symbol", "STZ", "name", "Constellation Brands, Inc."),
                Map.of("symbol", "ISRG", "name", "Intuitive Surgical, Inc."),
                Map.of("symbol", "TXN", "name", "Texas Instruments Incorporated"),
                Map.of("symbol", "SBUX", "name", "Starbucks Corporation"),
                Map.of("symbol", "COST", "name", "Costco Wholesale Corporation"),
                Map.of("symbol", "RBLX", "name", "Roblox Corporation"),
                Map.of("symbol", "TWTR", "name", "Twitter, Inc."),
                Map.of("symbol", "SPGI", "name", "S&P Global Inc."),
                Map.of("symbol", "MCK", "name", "McKesson Corporation"),
                Map.of("symbol", "PGR", "name", "The Progressive Corporation"),
                Map.of("symbol", "CTSH", "name", "Cognizant Technology Solutions Corporation"),
                Map.of("symbol", "DE", "name", "Deere & Company"),
                Map.of("symbol", "PEP", "name", "PepsiCo, Inc."),
                Map.of("symbol", "KHC", "name", "Kraft Heinz Company"),
                Map.of("symbol", "DHR", "name", "Danaher Corporation"),
                Map.of("symbol", "NKE", "name", "Nike Inc."),
                Map.of("symbol", "PRU", "name", "Prudential Financial, Inc."),
                Map.of("symbol", "WBA", "name", "Walgreens Boots Alliance"),
                Map.of("symbol", "AIG", "name", "American International Group, Inc."),
                Map.of("symbol", "CMCSA", "name", "Comcast Corporation"),
                Map.of("symbol", "AMT", "name", "American Tower Corporation"),
                Map.of("symbol", "MO", "name", "Altria Group, Inc."),
                Map.of("symbol", "PG", "name", "Procter & Gamble Co."),
                Map.of("symbol", "TGT", "name", "Target Corporation"),
                Map.of("symbol", "ADP", "name", "Automatic Data Processing, Inc."),
                Map.of("symbol", "LUV", "name", "Southwest Airlines Co."),
                Map.of("symbol", "SYK", "name", "Stryker Corporation"),
                Map.of("symbol", "GILD", "name", "Gilead Sciences, Inc."),
                Map.of("symbol", "CL", "name", "Colgate-Palmolive Company"),
                Map.of("symbol", "MMM", "name", "3M Company")
        );
    }
}
