package com.redz.financeportfolio.util;

import java.util.Map;

public class Companies {

    public static Map<String, String> COMPANYNAMES = Map.ofEntries(
            Map.entry("AAPL", "Apple Inc."),
            Map.entry("AMZN", "Amazon.com Inc."),
            Map.entry("GOOGL", "Alphabet Inc. (Google)"),
            Map.entry("MSFT", "Microsoft Corporation"),
            Map.entry("TSLA", "Tesla, Inc."),
            Map.entry("NFLX", "Netflix, Inc."),
            Map.entry("FB", "Meta Platforms (Facebook)"),
            Map.entry("NVDA", "NVIDIA Corporation"),
            Map.entry("BA", "The Boeing Company"),
            Map.entry("DIS", "The Walt Disney Company"),
            Map.entry("IBM", "International Business Machines Corporation"),
            Map.entry("SPY", "SPDR S&P 500 ETF Trust"),
            Map.entry("GOOG", "Alphabet Inc. (Google Class C)"),
            Map.entry("INTC", "Intel Corporation"),
            Map.entry("GS", "Goldman Sachs Group, Inc."),
            Map.entry("AMD", "Advanced Micro Devices, Inc."),
            Map.entry("BABA", "Alibaba Group"),
            Map.entry("V", "Visa Inc."),
            Map.entry("PYPL", "PayPal Holdings, Inc."),
            Map.entry("KO", "Coca-Cola Company"),
            Map.entry("TSM", "Taiwan Semiconductor Manufacturing Company"),
            Map.entry("PFE", "Pfizer Inc."),
            Map.entry("JNJ", "Johnson & Johnson"),
            Map.entry("WMT", "Walmart Inc."),
            Map.entry("GE", "General Electric"),
            Map.entry("COST", "Costco Wholesale Corporation"),
            Map.entry("ORCL", "Oracle Corporation"),
            Map.entry("CVX", "Chevron Corporation"),
            Map.entry("XOM", "Exxon Mobil Corporation"),
            Map.entry("MMM", "3M Company"),
            Map.entry("LMT", "Lockheed Martin Corporation"),
            Map.entry("MCD", "McDonald's Corporation"),
            Map.entry("NKE", "Nike, Inc."),
            Map.entry("AXP", "American Express Company"),
            Map.entry("T", "AT&T Inc."),
            Map.entry("VZ", "Verizon Communications Inc."),
            Map.entry("CAT", "Caterpillar Inc."),
            Map.entry("F", "Ford Motor Company"),
            Map.entry("ZTS", "Zoetis Inc."),
            Map.entry("MU", "Micron Technology, Inc."),
            Map.entry("TMO", "Thermo Fisher Scientific Inc."),
            Map.entry("ADBE", "Adobe Inc."),
            Map.entry("CSCO", "Cisco Systems, Inc."),
            Map.entry("AMAT", "Applied Materials, Inc."),
            Map.entry("MDT", "Medtronic plc"),
            Map.entry("BMY", "Bristol-Myers Squibb Company"),
            Map.entry("CVS", "CVS Health Corporation"),
            Map.entry("UNH", "UnitedHealth Group Incorporated"),
            Map.entry("NEE", "NextEra Energy, Inc."),
            Map.entry("BNS", "Bank of Nova Scotia"),
            Map.entry("MRK", "Merck & Co., Inc."),
            Map.entry("HON", "Honeywell International Inc."),
            Map.entry("MELI", "Mercado Libre, Inc."),
            Map.entry("ROST", "Ross Stores, Inc."),
            Map.entry("LOW", "Lowe's Companies, Inc."),
            Map.entry("WFC", "Wells Fargo & Company"),
            Map.entry("SCHW", "Charles Schwab Corporation"),
            Map.entry("PLD", "Prologis, Inc."),
            Map.entry("CME", "CME Group Inc."),
            Map.entry("STZ", "Constellation Brands, Inc."),
            Map.entry("ISRG", "Intuitive Surgical, Inc."),
            Map.entry("TXN", "Texas Instruments Incorporated"),
            Map.entry("SBUX", "Starbucks Corporation"),
            Map.entry("RBLX", "Roblox Corporation"),
            Map.entry("TWTR", "Twitter, Inc."),
            Map.entry("SPGI", "S&P Global Inc."),
            Map.entry("MCK", "McKesson Corporation"),
            Map.entry("PGR", "The Progressive Corporation"),
            Map.entry("CTSH", "Cognizant Technology Solutions Corporation"),
            Map.entry("DE", "Deere & Company"),
            Map.entry("PEP", "PepsiCo, Inc."),
            Map.entry("KHC", "Kraft Heinz Company"),
            Map.entry("DHR", "Danaher Corporation"),
            Map.entry("PRU", "Prudential Financial, Inc."),
            Map.entry("WBA", "Walgreens Boots Alliance"),
            Map.entry("AIG", "American International Group, Inc."),
            Map.entry("CMCSA", "Comcast Corporation"),
            Map.entry("AMT", "American Tower Corporation"),
            Map.entry("MO", "Altria Group, Inc."),
            Map.entry("PG", "Procter & Gamble Co."),
            Map.entry("TGT", "Target Corporation"),
            Map.entry("ADP", "Automatic Data Processing, Inc."),
            Map.entry("LUV", "Southwest Airlines Co."),
            Map.entry("SYK", "Stryker Corporation"),
            Map.entry("GILD", "Gilead Sciences, Inc."),
            Map.entry("CL", "Colgate-Palmolive Company")
    );

}